name: 'my_dbt_project'
version: '1.0'
config-version: 2

profile: 'default'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets: ["target"]

vars:
  environment: "dev"

repositories:
  - name: "my_repo"
    package-name: "my_package"
    path: "path/to/repo"
    git: "git@github.com:VarunServsoft/airbyte_demo.git"
    install-command: "pip install -r requirements.txt"

models:
  my_dbt_project:
    my_first_model:
      enabled: true
      materialized: view
      unique_key: id
      tags: ['tag1', 'tag2']
      description: "This is my first dbt model."
      columns:
        - name: id
          description: "The primary key for this table"
          tests:
            - unique
            - not_null
